[[redirects]]
from = "/api/*"
to = "https://apostolicanswers.onrender.com"
status = 200
force = true
headers = {Access-Control-Allow-Origin = "https://apostolicanswers.netlify.app", Access-Control-Allow-Credentials = "true"}